language: python
python:
- 3.8


#installation phase
  #before install
  #install
 install:
 - pip install -r requirements.txt
 

#script phase
  #before script
  #script
  script: 
  - python test_fruit.py
  - mkdir shortstory
  - cd shortstory
  - touch KKK
  - echo "It seems it works!"
  
  #after script
  
#after script phase 
  #after sucess
  #after failure

#deploy phase
  #before deploy
  #deploy
  #after deploy

