language: python
python:
- 3.8
script: python test_fruit.py

#git:
#  depth: 5


#installation phase
  #before install
  #install

#script phase
  #before script
  #after script
  
#after script phase 
  #after sucess
  #after failure

#deploy phase
  #before deploy
  #deploy
  #after deploy

#safelist
branches:
  only: 
  - main
#blocklist  
  except:
  - opt
#regular expresions can be used too  like - /[upt][a-q]*[t]\b//
  
env:
  - QA
  - PROD

#update nr 6
